import { Injectable } from '@nestjs/common'; import { PrismaService } from '../prisma/prisma.service'; import { AuthContext } from '../auth/auth.types';
@Injectable() export class NotificationsService { constructor(private p:PrismaService){} private school(a:AuthContext){if(!a.schoolId)throw new Error('School required');return a.schoolId}
async list(a:AuthContext){return this.p.notification.findMany({where:{schoolId:this.school(a),userId:a.userId},orderBy:{createdAt:'desc'}})}
async read(a:AuthContext,id:string){return this.p.notification.updateMany({where:{id,schoolId:this.school(a),userId:a.userId},data:{readAt:new Date()}})}
async preferences(a:AuthContext){return this.p.notificationPreference.findMany({where:{schoolId:this.school(a),userId:a.userId}})}
async setPreference(a:AuthContext,eventType:string,inAppEnabled:boolean,emailEnabled:boolean){return this.p.notificationPreference.upsert({where:{schoolId_userId_eventType:{schoolId:this.school(a),userId:a.userId,eventType}},update:{inAppEnabled,emailEnabled},create:{schoolId:this.school(a),userId:a.userId,eventType,inAppEnabled,emailEnabled}})}
async enqueue(schoolId:string,userId:string,eventType:string,payload:{title:string;body?:string;link?:string;confidential?:boolean},key:string){return this.p.notificationJob.upsert({where:{idempotencyKey:key},update:{},create:{schoolId,recipientUserId:userId,eventType,payload:payload as any,idempotencyKey:key}})}
async process(limit=50){const jobs=await this.p.notificationJob.findMany({where:{status:'PENDING',availableAt:{lte:new Date()}},take:limit,orderBy:{createdAt:'asc'}});for(const job of jobs){try{const pref=await this.p.notificationPreference.findUnique({where:{schoolId_userId_eventType:{schoolId:job.schoolId,userId:job.recipientUserId,eventType:job.eventType}}});const payload=job.payload as any;if(pref?.inAppEnabled!==false)await this.p.notification.upsert({where:{idempotencyKey:job.idempotencyKey},update:{},create:{schoolId:job.schoolId,userId:job.recipientUserId,eventType:job.eventType,title:payload.title,body:payload.confidential?'You have a confidential school update.':payload.body??'',link:payload.link,idempotencyKey:job.idempotencyKey}});await this.p.notificationJob.update({where:{id:job.id},data:{status:'DELIVERED',attempts:{increment:1}}})}catch(e){const attempts=job.attempts+1;await this.p.notificationJob.update({where:{id:job.id},data:{attempts,lastError:e instanceof Error?e.message:'Delivery failed',status:attempts>=3?'FAILED':'PENDING',availableAt:new Date(Date.now()+attempts*60_000)}})}}return {processed:jobs.length}}
}
