CREATE TYPE "NotificationChannel" AS ENUM ('IN_APP','EMAIL');
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING','DELIVERED','FAILED');
CREATE TABLE "notification_preferences" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"school_id" UUID NOT NULL,"user_id" UUID NOT NULL,"event_type" VARCHAR(120) NOT NULL,"in_app_enabled" BOOLEAN NOT NULL DEFAULT true,"email_enabled" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "notification_preferences_pkey" PRIMARY KEY("id"),CONSTRAINT "notification_preferences_school_id_user_id_event_type_key" UNIQUE("school_id","user_id","event_type"));
CREATE INDEX "notification_preferences_school_id_user_id_idx" ON "notification_preferences"("school_id","user_id");
CREATE TABLE "notifications" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"school_id" UUID NOT NULL,"user_id" UUID NOT NULL,"event_type" VARCHAR(120) NOT NULL,"title" VARCHAR(200) NOT NULL,"body" VARCHAR(1000) NOT NULL,"link" VARCHAR(500),"idempotency_key" VARCHAR(255) NOT NULL,"read_at" TIMESTAMPTZ(3),"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "notifications_pkey" PRIMARY KEY("id"),CONSTRAINT "notifications_idempotency_key_key" UNIQUE("idempotency_key"));
CREATE INDEX "notifications_school_id_user_id_created_at_idx" ON "notifications"("school_id","user_id","created_at");
CREATE TABLE "notification_jobs" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"school_id" UUID NOT NULL,"event_type" VARCHAR(120) NOT NULL,"recipient_user_id" UUID NOT NULL,"payload" JSONB NOT NULL,"idempotency_key" VARCHAR(255) NOT NULL,"status" "NotificationStatus" NOT NULL DEFAULT 'PENDING',"attempts" INTEGER NOT NULL DEFAULT 0,"available_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"last_error" TEXT,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "notification_jobs_pkey" PRIMARY KEY("id"),CONSTRAINT "notification_jobs_idempotency_key_key" UNIQUE("idempotency_key"));
CREATE INDEX "notification_jobs_status_available_at_idx" ON "notification_jobs"("status","available_at");
CREATE INDEX "notification_jobs_school_id_recipient_user_id_idx" ON "notification_jobs"("school_id","recipient_user_id");
