'use client';
import { FormEvent, useEffect, useState } from 'react';
import { WorkspaceNav } from '../../components/workspace-nav';
const api = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Report = { id: string; category: string; incidentDate: string; location: string | null; description: string; reporter: { displayName: string; email: string }; status: string; duplicateCandidateCount: number; abuseIndicator: boolean };
export default function SafetyIntakePage() { const [reports, setReports] = useState<Report[]>([]); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function load() { const r = await fetch(`${api}/safety/intake/reports`, { credentials: 'include' }); const d = await r.json(); if (r.ok) setReports(d); else setError(d?.error?.message ?? 'Confidential intake is unavailable.'); }
  useEffect(() => { void load(); }, []);
  async function update(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); setError(''); setNotice(''); const f = new FormData(event.currentTarget); const r = await fetch(`${api}/safety/intake/reports/${id}`, { method: 'PATCH', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status: f.get('status'), reporterNote: f.get('reporterNote') || undefined }) }); if (!r.ok) setError((await r.json())?.error?.message ?? 'Unable to update report.'); else { setNotice('Reporter-safe status update saved and audited.'); await load(); } }
  return <main className="app-shell text-slate-900"><div className="page-container"><WorkspaceNav /><header><p className="eyebrow">Restricted workspace</p><h1 className="page-title mt-2">Safeguarding intake</h1><p className="page-copy mt-3">Access to this page and every report view is audited. Do not share report details outside the documented safeguarding process.</p></header>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{notice && <p className="mt-5 rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}<div className="mt-7 space-y-5">{reports.map((report) => <article key={report.id} className="app-card p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold text-[#092d83]">{report.category} · {new Date(report.incidentDate).toLocaleDateString()}</h2><span className="status-pill bg-[#e8efff] text-[#092d83]">{report.status}</span></div><p className="mt-3 text-sm"><strong>Protected reporter:</strong> {report.reporter.displayName} ({report.reporter.email})</p><p className="mt-2 text-sm"><strong>Location:</strong> {report.location ?? 'Not provided'}</p><p className="mt-4 whitespace-pre-wrap leading-7">{report.description}</p>{(report.duplicateCandidateCount > 0 || report.abuseIndicator) && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Review indicator: {report.duplicateCandidateCount} similar recent submission(s). This is not an allegation or automated outcome.</p>}<form onSubmit={(event) => update(event, report.id)} className="mt-5 flex flex-wrap gap-3 border-t pt-4"><select name="status" defaultValue={report.status} className="rounded-lg border p-2"><option value="UNDER_REVIEW">Under review</option><option value="FOLLOW_UP">Follow up</option><option value="CLOSED">Closed</option></select><input name="reporterNote" minLength={3} maxLength={1000} className="min-w-64 flex-1 rounded-lg border p-2" placeholder="Safe, non-sensitive update for the reporter (optional)" /><button className="brand-button rounded-lg px-4 font-bold text-white">Save update</button></form></article>)}{!reports.length && !error && <p className="text-slate-500">No safety reports are awaiting review.</p>}</div></div></main>; }
